docker_login: &docker_login
    name: Docker login
    command: |
        docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD


version: 2
jobs:
    grnn:
        docker:
            - image: circleci/buildpack-deps
        steps:
            - checkout
            - setup_remote_docker
            - run:
                <<: *docker_login
            - run:
                name: Build
                working_directory: models/GRNN
                command: docker-compose -f docker-compose.test.yml build
            - run:
                name: Push to Docker Hub
                working_directory: models/GRNN
                command: docker-compose -f docker-compose.test.yml push
            - run:
                name: Run tests
                working_directory: models/GRNN
                command: docker-compose -f docker-compose.test.yml up --abort-on-container-exit

    jrnn:
        docker:
            - image: circleci/buildpack-deps
        steps:
            - checkout
            - setup_remote_docker
            - run:
                <<: *docker_login
            - run:
                name: Build
                working_directory: models/JRNN
                command: docker-compose -f docker-compose.test.yml build
            - run:
                name: Push to Docker Hub
                working_directory: models/JRNN
                command: docker-compose -f docker-compose.test.yml push
            - run:
                name: Run tests
                working_directory: models/JRNN
                command: docker-compose -f docker-compose.test.yml up --abort-on-container-exit

workflows:
    version: 2
    all_tests:
        jobs:
            - grnn
            - jrnn
