docker_login: &docker_login
    name: Docker login
    command: |
        echo $DOCKER_HUB_PWD | docker login -u $DOCKER_HUB_USER_ID --password-stdin


version: 2.1
jobs:
    ngram:
        machine:
            image: circleci/classic:latest
        steps:
            - checkout
            - run:
                name: Check for relevant code updates
                command: ./scripts/check_for_updates.sh $CIRCLE_JOB << pipeline.git.base_revision >> << pipeline.git.revision >>
            - run:
                <<: *docker_login
            - add_ssh_keys:
                fingerprints:
                    - "88:36:05:01:d6:98:05:43:e3:e4:e3:d3:a3:67:e9:29"
            - run:
                name: Build
                command: docker build -t cpllab/language-models:ngram -f models/ngram/Dockerfile --build-arg CPL_SSH_PRV_KEY="$(cat ~/.ssh/id_rsa_88360501d6980543e3e4e3d3a367e929)" .
            # - run:
            #     name: Push to Docker Hub
            #     command: docker push cpllab/language-models:ngram
            - run:
                name: Run tests
                working_directory: models/ngram
                command: docker run --rm -v test.py:/test.py -v docs/schemas:/schemas cpllab/language-models:ngram python /test.py
    GRNN:
        machine:
            image: circleci/classic:latest
        steps:
            - checkout
            - run:
                name: Check for relevant code updates
                command: ./scripts/check_for_updates.sh $CIRCLE_JOB << pipeline.git.base_revision >> << pipeline.git.revision >>
            - run:
                <<: *docker_login
            - run:
                name: Build
                command: docker build -t cpllab/language-models:grnn -f models/GRNN/Dockerfile .
            - run:
                name: Run tests
                command: docker run --rm -v test.py:/test.py -v docs/schemas:/schemas cpllab/language-models:grnn python /test.py
            # - run:
            #     name: Push to Docker Hub
            #     command: docker push cpllab/language-models:grnn

    JRNN:
        machine:
            image: circleci/classic:latest
        steps:
            - checkout
            - run:
                name: Check for relevant code updates
                command: ./scripts/check_for_updates.sh $CIRCLE_JOB << pipeline.git.base_revision >> << pipeline.git.revision >>
            - run:
                <<: *docker_login
            - run:
                name: Build
                command: docker build -t cpllab/language-models:jrnn -f models/JRNN/Dockerfile .
            # - run:
            #     name: Push to Docker Hub
            #     command: docker push cpllab/language-models:jrnn
            - run:
                name: Run tests
                working_directory: models/JRNN
                command: docker run --rm -v test.py:/test.py -v docs/schemas:/schemas cpllab/language-models:jrnn python /test.py

    RNNG:
        machine:
            image: circleci/classic:latest
        steps:
            - checkout
            - run:
                name: Check for relevant code updates
                command: ./scripts/check_for_updates.sh $CIRCLE_JOB << pipeline.git.base_revision >> << pipeline.git.revision >>

            - run:
                <<: *docker_login
            - add_ssh_keys:
                fingerprints:
                    - "88:36:05:01:d6:98:05:43:e3:e4:e3:d3:a3:67:e9:29"
            - run:
                name: Build
                command: docker build -t cpllab/language-models:rnng -f models/RNNG/Dockerfile --build-arg CPL_SSH_PRV_KEY="$(cat ~/.ssh/id_rsa_88360501d6980543e3e4e3d3a367e929)" .
            # - run:
            #     name: Push to Docker Hub
            #     command: docker push cpllab/language-models:rnng
            - run:
                name: Run tests
                working_directory: models/RNNG
                command: docker run --rm -v test.py:/test.py -v docs/schemas:/schemas cpllab/language-models:rnng python /test.py

    ordered-neurons:
        machine:
            image: circleci/classic:latest
        steps:
            - checkout
            - run:
                name: Check for relevant code updates
                command: ./scripts/check_for_updates.sh $CIRCLE_JOB << pipeline.git.base_revision >> << pipeline.git.revision >>

            - run:
                <<: *docker_login
            - add_ssh_keys:
                fingerprints:
                    - "88:36:05:01:d6:98:05:43:e3:e4:e3:d3:a3:67:e9:29"
            - run:
                name: Build
                command: docker build -t cpllab/language-models:ordered-neurons -f models/ordered-neurons/Dockerfile --build-arg CPL_SSH_PRV_KEY="$(cat ~/.ssh/id_rsa_88360501d6980543e3e4e3d3a367e929)" .
            # - run:
            #     name: Push to Docker Hub
            #     command: docker push cpllab/language-models:ordered-neurons
            - run:
                name: Run tests
                working_directory: models/ordered-neurons
                command: docker run --rm -v test.py:/test.py -v docs/schemas:/schemas cpllab/language-models:ordered-neurons python /test.py

    gpt2:
        machine:
            image: circleci/classic:latest
        steps:
            - checkout
            - run:
                name: Check for relevant code updates
                command: ./scripts/check_for_updates.sh $CIRCLE_JOB << pipeline.git.base_revision >> << pipeline.git.revision >>

            - run:
                <<: *docker_login
            - run:
                name: Build
                command: docker build -t cpllab/language-models:gpt2 -f models/gpt2/Dockerfile .
            - run:
                name: Run tests
                working_directory: models/gpt2
                command: docker run --rm -v test.py:/test.py -v docs/schemas:/schemas cpllab/language-models:gpt2 python /test.py
            # - run:
            #     name: Push to Docker Hub
            #     command: docker push cpllab/language-models:gpt2

    transformer-xl:
        machine:
            image: circleci/classic:latest
        steps:
            - checkout
            - run:
                name: Check for relevant code updates
                command: ./scripts/check_for_updates.sh $CIRCLE_JOB << pipeline.git.base_revision >> << pipeline.git.revision >>

            - run:
                <<: *docker_login
            - run:
                name: Build
                command: docker build -t cpllab/language-models:transformer-xl -f models/transformer-xl/Dockerfile .
            - run:
                name: Run tests
                working_directory: models/transformer-xl
                command: docker run --rm -v test.py:/test.py -v docs/schemas:/schemas cpllab/language-models:transformer-xl python /test.py
            # - run:
            #     name: Push to Docker Hub
            #     command: docker push cpllab/language-models:transformer-xl



workflows:
    version: 2
    build_all:
        jobs:
            - ngram
            - GRNN
            - JRNN
            - RNNG
            - ordered-neurons
            - gpt2
            - transformer-xl
