docker_login: &docker_login
    name: Docker login
    command: |
        echo $DOCKER_HUB_PWD | docker login -u $DOCKER_HUB_USER_ID --password-stdin


version: 2
jobs:
    ngram:
        machine:
            image: circleci/classic:latest
        steps:
            - checkout
            - run:
                name: Check for relevant code updates
                command: ./tools/check_for_updates.sh $CIRCLE_JOB $CIRCLE_COMPARE_URL $CIRCLE_SHA1
            - run:
                <<: *docker_login
            - add_ssh_keys:
                fingerprints:
                    - "88:36:05:01:d6:98:05:43:e3:e4:e3:d3:a3:67:e9:29"
            - run:
                name: Build
                command: docker build -t cpllab/language-models:ngram -f models/ngram/Dockerfile --build-arg CPL_SSH_PRV_KEY="$(cat ~/.ssh/id_rsa_88360501d6980543e3e4e3d3a367e929)" .
            - run:
                name: Push to Docker Hub
                command: docker push cpllab/language-models:ngram
            - run:
                name: Run tests
                working_directory: models/ngram
                command: docker-compose -f docker-compose.test.yml up --abort-on-container-exit
    grnn:
        machine:
            image: circleci/classic:latest
        steps:
            - checkout
            - run:
                name: Check for relevant code updates
                command: ./tools/check_for_updates.sh $CIRCLE_JOB
            - run:
                <<: *docker_login
            - run:
                name: Build
                command: docker build -t cpllab/language-models:grnn -f models/GRNN/Dockerfile .
            - run:
                name: Run tests
                working_directory: models/GRNN
                command: docker-compose -f docker-compose.test.yml up --abort-on-container-exit
            - run:
                name: Push to Docker Hub
                command: docker push cpllab/language-models:grnn

    jrnn:
        machine:
            image: circleci/classic:latest
        steps:
            - checkout
            - run:
                name: Check for relevant code updates
                command: ./tools/check_for_updates.sh $CIRCLE_JOB
            - run:
                <<: *docker_login
            - run:
                name: Build
                command: docker build -t cpllab/language-models:jrnn -f models/JRNN/Dockerfile .
            - run:
                name: Push to Docker Hub
                command: docker push cpllab/language-models:jrnn
            - run:
                name: Run tests
                working_directory: models/JRNN
                command: docker-compose -f docker-compose.test.yml up --abort-on-container-exit

    rnng:
        machine:
            image: circleci/classic:latest
        steps:
            - checkout
            - run:
                name: Check for relevant code updates
                command: ./tools/check_for_updates.sh $CIRCLE_JOB

            - run:
                <<: *docker_login
            - add_ssh_keys:
                fingerprints:
                    - "88:36:05:01:d6:98:05:43:e3:e4:e3:d3:a3:67:e9:29"
            - run:
                name: Build
                command: docker build -t cpllab/language-models:rnng -f models/RNNG/Dockerfile --build-arg CPL_SSH_PRV_KEY="$(cat ~/.ssh/id_rsa_88360501d6980543e3e4e3d3a367e929)" .
            - run:
                name: Push to Docker Hub
                command: docker push cpllab/language-models:rnng
            - run:
                name: Run tests
                working_directory: models/RNNG
                command: docker-compose -f docker-compose.test.yml up --abort-on-container-exit

    action-lstm:
        machine:
            image: circleci/classic:latest
        steps:
            - checkout
            - run:
                name: Check for relevant code updates
                command: ./tools/check_for_updates.sh $CIRCLE_JOB

            - run:
                <<: *docker_login
            - add_ssh_keys:
                fingerprints:
                    - "88:36:05:01:d6:98:05:43:e3:e4:e3:d3:a3:67:e9:29"
            - run:
                name: Build
                command: docker build -t cpllab/language-models:action-lstm -f models/Action-LSTM/Dockerfile --build-arg CPL_SSH_PRV_KEY="$(cat ~/.ssh/id_rsa_88360501d6980543e3e4e3d3a367e929)" .
            - run:
                name: Push to Docker Hub
                command: docker push cpllab/language-models:action-lstm
            - run:
                name: Run tests
                working_directory: models/Action-LSTM
                command: docker-compose -f docker-compose.test.yml up --abort-on-container-exit

    ordered-neurons:
        machine:
            image: circleci/classic:latest
        steps:
            - checkout
            - run:
                name: Check for relevant code updates
                command: ./tools/check_for_updates.sh $CIRCLE_JOB

            - run:
                <<: *docker_login
            - add_ssh_keys:
                fingerprints:
                    - "88:36:05:01:d6:98:05:43:e3:e4:e3:d3:a3:67:e9:29"
            - run:
                name: Build
                command: docker build -t cpllab/language-models:ordered-neurons -f models/ordered-neurons/Dockerfile --build-arg CPL_SSH_PRV_KEY="$(cat ~/.ssh/id_rsa_88360501d6980543e3e4e3d3a367e929)" .
            - run:
                name: Push to Docker Hub
                command: docker push cpllab/language-models:ordered-neurons
            - run:
                name: Run tests
                working_directory: models/ordered-neurons
                command: docker-compose -f docker-compose.test.yml up --abort-on-container-exit

    ordered-neurons-cased-ptb:
        machine:
            image: circleci/classic:latest
        steps:
            - checkout
            - run:
                name: Check for relevant code updates
                command: ./tools/check_for_updates.sh $CIRCLE_JOB

            - run:
                <<: *docker_login
            - add_ssh_keys:
                fingerprints:
                    - "88:36:05:01:d6:98:05:43:e3:e4:e3:d3:a3:67:e9:29"
            - run:
                name: Build
                command: docker build -t cpllab/language-models:ordered-neurons-cased-ptb -f models/ordered-neurons/Dockerfile --build-arg CHECKPOINT_NAME=jennhu-ptb-20191108 --build-arg CPL_SSH_PRV_KEY="$(cat ~/.ssh/id_rsa_88360501d6980543e3e4e3d3a367e929)" .
            - run:
                name: Push to Docker Hub
                command: docker push cpllab/language-models:ordered-neurons-cased-ptb

    pytorch-transformers:
        machine:
            image: circleci/classic:latest
        steps:
            - checkout
            - run:
                name: Check for relevant code updates
                command: ./tools/check_for_updates.sh $CIRCLE_JOB

            - run:
                <<: *docker_login
            - run:
                name: Build
                command: docker build -t cpllab/language-models:pytorch-transformers -f models/pytorch-transformers/Dockerfile .
            - run:
                name: Push to Docker Hub
                command: docker push cpllab/language-models:pytorch-transformers

    gpt2:
        machine:
            image: circleci/classic:latest
        steps:
            - checkout
            - run:
                name: Check for relevant code updates
                command: ./tools/check_for_updates.sh $CIRCLE_JOB

            - run:
                <<: *docker_login
            - run:
                name: Build
                command: docker build -t cpllab/language-models:gpt2 -f models/gpt2/Dockerfile .
            - run:
                name: Run tests
                working_directory: models/gpt2
                command: docker-compose -f docker-compose.test.yml up --abort-on-container-exit
            - run:
                name: Push to Docker Hub
                command: docker push cpllab/language-models:gpt2

    transformer-xl:
        machine:
            image: circleci/classic:latest
        steps:
            - checkout
            - run:
                name: Check for relevant code updates
                command: ./tools/check_for_updates.sh $CIRCLE_JOB

            - run:
                <<: *docker_login
            - run:
                name: Build
                command: docker build -t cpllab/language-models:transformer-xl -f models/transformer-xl/Dockerfile .
            - run:
                name: Run tests
                working_directory: models/transformer-xl
                command: docker-compose -f docker-compose.test.yml up --abort-on-container-exit
            - run:
                name: Push to Docker Hub
                command: docker push cpllab/language-models:transformer-xl

    roberta:
        machine:
            image: circleci/classic:latest
        steps:
            - checkout
            - run:
                name: Check for relevant code updates
                command: ./tools/check_for_updates.sh $CIRCLE_JOB

            - run:
                <<: *docker_login
            - run:
                name: Build
                command: docker build -t cpllab/language-models:roberta -f models/roberta/Dockerfile .
            - run:
                name: Push to Docker Hub
                command: docker push cpllab/language-models:roberta
            - run:
                name: Run tests
                working_directory: models/roberta
                command: docker-compose -f docker-compose.test.yml up --abort-on-container-exit

    tiny-lstm:
        machine:
            image: circleci/classic:latest
        steps:
            - checkout
            - run:
                name: Check for relevant code updates
                command: ./tools/check_for_updates.sh $CIRCLE_JOB

            - run:
                <<: *docker_login
            - add_ssh_keys:
                fingerprints:
                    - "88:36:05:01:d6:98:05:43:e3:e4:e3:d3:a3:67:e9:29"
            - run:
                name: Build
                command: docker build -t cpllab/language-models:tiny-lstm -f models/tiny-LSTM/Dockerfile --build-arg CPL_SSH_PRV_KEY="$(cat ~/.ssh/id_rsa_88360501d6980543e3e4e3d3a367e929)" .
            - run:
                name: Push to Docker Hub
                command: docker push cpllab/language-models:tiny-lstm
            - run:
                name: Run tests
                working_directory: models/tiny-LSTM
                command: docker-compose -f docker-compose.test.yml up --abort-on-container-exit



workflows:
    version: 2
    build_all:
        jobs:
            - ngram
            - grnn
            - jrnn
            - rnng
            - action-lstm
            - ordered-neurons
            - ordered-neurons-cased-ptb
            - pytorch-transformers
            - gpt2
            - transformer-xl
            - roberta
            - tiny-lstm
