version: 2
jobs:
    grnn:
        docker:
            - image: docker/compose
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: Run tests
                working_directory: models/GRNN
                command: docker-compose -f docker-compose.test.yml up --abort-on-container-exit
