docker_login: &docker_login
    name: Docker login
    command: |
        echo $DOCKER_HUB_PWD | docker login -u $DOCKER_HUB_USER_ID --password-stdin


version: 2
jobs:
    grnn:
        machine:
            image: circleci/classic:latest
            docker_layer_caching: true
        steps:
            - checkout
            - run:
                <<: *docker_login
            - run:
                name: Build
                working_directory: models/GRNN
                command: docker build -t cpllab/language-models:grnn .
            - run:
                name: Push to Docker Hub
                working_directory: models/GRNN
                command: docker push cpllab/language-models:grnn
            - run:
                name: Run tests
                working_directory: models/GRNN
                command: docker-compose -f docker-compose.test.yml up --abort-on-container-exit

    jrnn:
        machine:
            image: circleci/classic:latest
            docker_layer_caching: true
        steps:
            - checkout
            - run:
                <<: *docker_login
            - run:
                name: Build
                working_directory: models/JRNN
                command: docker build -t cpllab/language-models:jrnn .
            - run:
                name: Push to Docker Hub
                working_directory: models/JRNN
                command: docker push cpllab/language-models:jrnn
            - run:
                name: Run tests
                working_directory: models/JRNN
                command: docker-compose -f docker-compose.test.yml up --abort-on-container-exit

    rnng:
        machine:
            image: circleci/classic:latest
            docker_layer_caching: true
        steps:
            - checkout
            - run:
                <<: *docker_login
            - run:
                name: Build
                working_directory: models/RNNG
                command: docker build -t cpllab/language-models:rnng .
            - run:
                name: Push to Docker Hub
                working_directory: models/RNNG
                command: docker push cpllab/language-models:rnng
            # - run:
            #     name: Run tests
            #     working_directory: models/JRNN
            #     command: docker-compose -f docker-compose.test.yml up --abort-on-container-exit

    transformer-xl:
        machine:
            image: circleci/classic:latest
            docker_layer_caching: true
        steps:
            - checkout
            - run:
                <<: *docker_login
            - run:
                name: Build
                working_directory: models/transformer-xl
                command: docker build -t cpllab/language-models:transformer-xl .
            - run:
                name: Push to Docker Hub
                working_directory: models/transformer-xl
                command: docker push cpllab/language-models:transformer-xl
            # - run:
            #     name: Run tests
            #     working_directory: models/JRNN
            #     command: docker-compose -f docker-compose.test.yml up --abort-on-container-exit

workflows:
    version: 2
    all_tests:
        jobs:
            - grnn
            - jrnn
            - rnng
            - transformer-xl
