version: 2
jobs:
    grnn:
        docker:
            - image: circleci/buildpack-deps
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: Run tests
                working_directory: models/GRNN
                command: docker-compose -f docker-compose.test.yml up --abort-on-container-exit

    jrnn:
        docker:
            - image: circleci/buildpack-deps
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: Run tests
                working_directory: models/JRNN
                command: docker-compose -f docker-compose.test.yml up --abort-on-container-exit

workflows:
    version: 2
    all_tests:
        jobs:
            - grnn
            - jrnn
