docker_login: &docker_login
    name: Docker login
    command: |
        echo $DOCKER_HUB_PWD | docker login -u $DOCKER_HUB_USER_ID --password-stdin


version: 2
jobs:
    grnn:
        machine:
            image: circleci/classic:latest
            docker_layer_caching: true
        steps:
            - checkout
            - run:
                <<: *docker_login
            - run:
                name: Build
                command: docker build -t cpllab/language-models:grnn -f models/GRNN/Dockerfile .
            - run:
                name: Run tests
                working_directory: models/GRNN
                command: docker-compose -f docker-compose.test.yml up --abort-on-container-exit
            - run:
                name: Push to Docker Hub
                command: docker push cpllab/language-models:grnn

    jrnn:
        machine:
            image: circleci/classic:latest
            docker_layer_caching: true
        steps:
            - checkout
            - run:
                <<: *docker_login
            - run:
                name: Build
                command: docker build -t cpllab/language-models:jrnn -f models/JRNN/Dockerfile .
            - run:
                name: Push to Docker Hub
                command: docker push cpllab/language-models:jrnn
            - run:
                name: Run tests
                working_directory: models/JRNN
                command: docker-compose -f docker-compose.test.yml up --abort-on-container-exit

    rnng:
        machine:
            image: circleci/classic:latest
            docker_layer_caching: true
        steps:
            - checkout
            - run:
                <<: *docker_login
            - add_ssh_keys:
                fingerprints:
                    - "88:36:05:01:d6:98:05:43:e3:e4:e3:d3:a3:67:e9:29"
            - run:
                name: Build
                command: docker build -t cpllab/language-models:rnng -f models/RNNG/Dockerfile --build-arg CPL_SSH_PRV_KEY="$(cat ~/.ssh/id_rsa_88360501d6980543e3e4e3d3a367e929)" .
            - run:
                name: Push to Docker Hub
                command: docker push cpllab/language-models:rnng
            - run:
                name: Run tests
                working_directory: models/RNNG
                command: docker-compose -f docker-compose.test.yml up --abort-on-container-exit

    transformer-xl:
        machine:
            image: circleci/classic:latest
            docker_layer_caching: true
        steps:
            - checkout
            - run:
                <<: *docker_login
            - run:
                name: Build
                command: docker build -t cpllab/language-models:transformer-xl -f models/transformer-xl/Dockerfile .
            - run:
                name: Run tests
                working_directory: models/transformer-xl
                command: docker-compose -f docker-compose.test.yml up --abort-on-container-exit
            - run:
                name: Push to Docker Hub
                command: docker push cpllab/language-models:transformer-xl

workflows:
    version: 2
    all_tests:
        jobs:
            - grnn
            - jrnn
            - rnng
            - transformer-xl
